name: build bootx64.efi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build in Docker
      run: docker build -t apple_set_os_loader . && docker run --rm -v $(pwd):/build apple_set_os_loader
    - uses: actions/upload-artifact@v4
      with:
        name: release bootx64.efi
        path: bootx64.efi
